### ISSUE TITLE
Enhancement request: Colored timeout/lost packet

### ISSUE THREAD

**Issue by gustavhelgi** [famzah/ping-multi-ext#1]
Hi,

As discussed in your previous project i´m opening an enhancement request for this one instead as this is the project you are focusing on :). I tested it and it looks great so would like to request if we can do some at least simple coloring of timeout/lost packets :).

There are scenarios i have long test lists or multiple windows to multiple hosts to verify connections. Would be great to have a RED coloring on the X or "host line" line so it can be spotted quicker among multiple windows/lines.

As a side note it could be taken further to add color to enhance spotting issues but not really a request just something to think about if you want to take it further :)
Like orange to spot changes like 30% increase in RTT
Or have the host change color from RED (during) to orange to yellow to white depending on length since packetloss.

Again thanks for this,

Gustav

**Comment by famzah** [comment]
I've released version 1.0.8 which colors the hostname in red on errors. This is done only for the last (current) packet. The history line hasn't been changed. I believe that errors are well visible in the history without coloring: "." vs. "E" or "?" characters.

You can update to the latest version by simply reinstalling via pip:
```
pip3 install ping-multi-ext
```

Let me know what you think.

**Comment by famzah** [comment]
> As a side note it could be taken further to add color to enhance spotting issues but not really a request just something to think about if you want to take it further :)

It's easy to trick me into dreaming for tons of new features :) After careful consideration I think that the following should be enough to spot unexpected changes in the RTT:
- add the option `--stats-outliner-stdev`: a coefficient which determines how many standard deviations of the average will be considered an alarm state; for example, in a normal distribution 68%, 95%, and 99.7% of the values lie within one, two, and three standard deviations of the mean, respectively; default is 0 which disables this alarm
- in the history line color the "." characters _yellow_ or _green_ depending if they are < or > than "avg + X\*stdev" (where X is the value of `--stats-outliner-stdev`); for the last (current) packet also color the hostname; "." characters with RTT which are within the expected "avg + X\*stdev" are left uncolored (white)
- add the option `--stats-warm-up`: no alarms are activated until the specified count of packets are successfully _received_; this prevents false alarms when the ping has just been started and we don't have enough statistical data; default is 10

---

Something additional that I will not implement mainly because we rarely monitor the hosts for so long time that we would experience the following problem. I haven't needed this in my practice either, though theoretically it could be useful.

Outliners (and normal data) change both "avg" and "stdev". Those stats could drift a lot without noticing this even if we color the outliners. For example, average RTT could start small and get much bigger with time if the mere 5 ms is added for every RTT. We will color the outliners during the progress but the drift from average 100 ms to 500 ms wouldn't eventually be noticed if after enough time the RTT stabilizes at 500 ms with no outliners.

We could manually define a threshold value for `--stats-max-avg`, `--stats-max-loss` and/or `--stats-max-stdev`. Support this as general options (`--stats-max-avg`) and also per hostname (like "google.com,max-avg=40").

The problem is mainly with "avg" and "stdev" because we have no good visibility in the history of the numeric values. If the RTT is within the expected timeout, we only see a "." character. So if avg/stdev gets bigger or smaller we should alarm. But the question is where to display the alarm and what to consider a problem automatically. Do we have a look-back period that we consider the last OK state and then compare it with the current period? Or we always compare to the first few `--stats-warm-up` period values. For example, if we started with an average RTT of 100 ms and stdev of 5 for a host, do we raise an alarm if its current average/stdev change enough (smaller or bigger) compared to this initial average/stdev? Do we ever adjust the average/stdev to which we compare the current average/stdev?

**Comment by famzah** [comment]
I am closing this due to lack of feedback.
